/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdfprinterexample.ui;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOError;
import java.io.IOException;

/**
 *
 * @author flaw-
 */
public class BillDemo extends javax.swing.JFrame {

    /**
     * Creates new form BillDemo
     */
    public BillDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill_panel = new javax.swing.JPanel();
        lbl_college_name = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        sp_bottom = new javax.swing.JSeparator();
        lbl_name = new javax.swing.JLabel();
        lbl_name_data = new javax.swing.JLabel();
        lbl_semester = new javax.swing.JLabel();
        lbl_semester_data = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        lbl_year_data = new javax.swing.JLabel();
        lbl_month = new javax.swing.JLabel();
        lbl_month_data = new javax.swing.JLabel();
        sp_top = new javax.swing.JSeparator();
        lbl_fee_type = new javax.swing.JLabel();
        lbl_fee_type_data = new javax.swing.JLabel();
        lbl_actual_fee = new javax.swing.JLabel();
        lbl_actual_fee_data = new javax.swing.JLabel();
        lbl_discount = new javax.swing.JLabel();
        lbl_discount_data = new javax.swing.JLabel();
        lbl_previous_dues = new javax.swing.JLabel();
        lbl_previous_dues_data = new javax.swing.JLabel();
        lbl_total_fee = new javax.swing.JLabel();
        lbl_total_fee_data = new javax.swing.JLabel();
        sp_center = new javax.swing.JSeparator();
        lbl_issued_by = new javax.swing.JLabel();
        lbl_issued_by_data = new javax.swing.JLabel();
        lbl_issued_date = new javax.swing.JLabel();
        lbl_issued_date_data = new javax.swing.JLabel();
        lbl_signature = new javax.swing.JLabel();
        lbl_signature_data = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_college_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_college_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_college_name.setText("DAV College");

        lbl_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_address.setText("Dhobighat, Lalitpur, Nepal");

        sp_bottom.setBackground(new java.awt.Color(0, 0, 0));
        sp_bottom.setForeground(new java.awt.Color(0, 0, 0));
        sp_bottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_name.setText("Name:");

        lbl_name_data.setText("Sandesh Tamang");

        lbl_semester.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_semester.setText("Semester:");

        lbl_semester_data.setText("Sixth Semester");

        lbl_year.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_year.setText("Year:");

        lbl_year_data.setText("2025");

        lbl_month.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_month.setText("Month:");

        lbl_month_data.setText("March");

        sp_top.setBackground(new java.awt.Color(0, 0, 0));
        sp_top.setForeground(new java.awt.Color(0, 0, 0));
        sp_top.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_fee_type.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fee_type.setText("Fee Type:");

        lbl_fee_type_data.setText("Monthly Semester Fee");

        lbl_actual_fee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_actual_fee.setText("Actual Fee:");

        lbl_actual_fee_data.setText("6000.00");

        lbl_discount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_discount.setText("Discount:");

        lbl_discount_data.setText("1200.00");

        lbl_previous_dues.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_previous_dues.setText("Previous Dues:");

        lbl_previous_dues_data.setText("3200.00");

        lbl_total_fee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_total_fee.setText("Total Fee:");

        lbl_total_fee_data.setText("8000.00");

        sp_center.setBackground(new java.awt.Color(0, 0, 0));
        sp_center.setForeground(new java.awt.Color(0, 0, 0));
        sp_center.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_issued_by.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_issued_by.setText("Issued By:");

        lbl_issued_by_data.setText("Manoj Gajurel");

        lbl_issued_date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_issued_date.setText("Issued Date:");

        lbl_issued_date_data.setText("2025-03-18");

        lbl_signature.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_signature.setText("Signature:");

        lbl_signature_data.setText("_____________________________________");

        javax.swing.GroupLayout bill_panelLayout = new javax.swing.GroupLayout(bill_panel);
        bill_panel.setLayout(bill_panelLayout);
        bill_panelLayout.setHorizontalGroup(
            bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bill_panelLayout.createSequentialGroup()
                        .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_college_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(bill_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_semester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_month, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_month_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_year_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_semester_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_name_data, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))
                            .addComponent(sp_bottom, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(bill_panelLayout.createSequentialGroup()
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bill_panelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bill_panelLayout.createSequentialGroup()
                                .addComponent(lbl_fee_type, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_fee_type_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bill_panelLayout.createSequentialGroup()
                                .addComponent(lbl_actual_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_actual_fee_data, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                            .addGroup(bill_panelLayout.createSequentialGroup()
                                .addComponent(lbl_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_discount_data, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                            .addGroup(bill_panelLayout.createSequentialGroup()
                                .addComponent(lbl_previous_dues, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_previous_dues_data, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                            .addGroup(bill_panelLayout.createSequentialGroup()
                                .addComponent(lbl_total_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_total_fee_data, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                    .addGroup(bill_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbl_issued_by, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_issued_by_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bill_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbl_issued_date, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_issued_date_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bill_panelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbl_signature, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_signature_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bill_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_top)
                    .addContainerGap()))
            .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bill_panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_center)
                    .addContainerGap()))
        );
        bill_panelLayout.setVerticalGroup(
            bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_college_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_address)
                .addGap(27, 27, 27)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(lbl_name_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_semester)
                    .addComponent(lbl_semester_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_year)
                    .addComponent(lbl_year_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_month_data)
                    .addComponent(lbl_month))
                .addGap(42, 42, 42)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fee_type)
                    .addComponent(lbl_fee_type_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_actual_fee)
                    .addComponent(lbl_actual_fee_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_discount)
                    .addComponent(lbl_discount_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_previous_dues)
                    .addComponent(lbl_previous_dues_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total_fee)
                    .addComponent(lbl_total_fee_data))
                .addGap(18, 18, 18)
                .addComponent(sp_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_issued_by)
                    .addComponent(lbl_issued_by_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_issued_date)
                    .addComponent(lbl_issued_date_data))
                .addGap(18, 18, 18)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_signature)
                    .addComponent(lbl_signature_data))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bill_panelLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(sp_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
            .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bill_panelLayout.createSequentialGroup()
                    .addContainerGap(228, Short.MAX_VALUE)
                    .addComponent(sp_center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(292, 292, 292)))
        );

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bill_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_print)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bill_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_print)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        BufferedImage bf = new BufferedImage(this.bill_panel.getWidth(),
                this.bill_panel.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = bf.createGraphics();
        this.bill_panel.printAll(g2d);
        g2d.dispose();

        Document doc = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(doc, new FileOutputStream("C:/Users/flaw-/Downloads/bill.pdf"));
            doc.open();
            Image img = Image.getInstance(bf, null);
            doc.add(img);
            System.out.println("Bill Created Successfully!!");
        } catch (DocumentException | FileNotFoundException e) {
            System.out.println("Error: " + e.getMessage());
        } catch (IOException e) {
            System.out.println("Error: " + e.getMessage());
        } finally {
            doc.close();
        }
    }//GEN-LAST:event_btn_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bill_panel;
    private javax.swing.JButton btn_print;
    private javax.swing.JLabel lbl_actual_fee;
    private javax.swing.JLabel lbl_actual_fee_data;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_college_name;
    private javax.swing.JLabel lbl_discount;
    private javax.swing.JLabel lbl_discount_data;
    private javax.swing.JLabel lbl_fee_type;
    private javax.swing.JLabel lbl_fee_type_data;
    private javax.swing.JLabel lbl_issued_by;
    private javax.swing.JLabel lbl_issued_by_data;
    private javax.swing.JLabel lbl_issued_date;
    private javax.swing.JLabel lbl_issued_date_data;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_month_data;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name_data;
    private javax.swing.JLabel lbl_previous_dues;
    private javax.swing.JLabel lbl_previous_dues_data;
    private javax.swing.JLabel lbl_semester;
    private javax.swing.JLabel lbl_semester_data;
    private javax.swing.JLabel lbl_signature;
    private javax.swing.JLabel lbl_signature_data;
    private javax.swing.JLabel lbl_total_fee;
    private javax.swing.JLabel lbl_total_fee_data;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JLabel lbl_year_data;
    private javax.swing.JSeparator sp_bottom;
    private javax.swing.JSeparator sp_center;
    private javax.swing.JSeparator sp_top;
    // End of variables declaration//GEN-END:variables
}
